"""Add chunk metadata fields

Revision ID: ba1b6de6ba27
Revises: d5d68c0b7a1c
Create Date: 2026-07-06 14:55:09.562075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1b6de6ba27'
down_revision: Union[str, Sequence[str], None] = 'd5d68c0b7a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('chunk', sa.Column('course_code', sa.String(length=50), nullable=True))
    op.add_column('chunk', sa.Column('chunk_type', sa.String(length=50), nullable=True))
    op.add_column('chunk', sa.Column('semester', sa.String(length=50), nullable=True))
    op.add_column('chunk', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'credits')
    op.drop_column('chunk', 'semester')
    op.drop_column('chunk', 'chunk_type')
    op.drop_column('chunk', 'course_code')
    op.drop_column('chunk', 'title')
    # ### end Alembic commands ###
