"""add verification_file_url to university

Revision ID: ccbdbf50f1b2
Revises: d13de0802292
Create Date: 2026-06-25 00:53:35.884264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccbdbf50f1b2'
down_revision: Union[str, Sequence[str], None] = 'd13de0802292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.add_column('students', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('university', sa.Column('verification_file_url', sa.String(length=255), server_default='default.pdf', nullable=False))
    op.add_column('university', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('university', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.alter_column('university', 'country',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('university', 'country',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('university', 'is_email_verified')
    op.drop_column('university', 'status')
    op.drop_column('university', 'verification_file_url')
    op.drop_column('students', 'is_email_verified')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    # ### end Alembic commands ###
