"""add_rejection_reason_to_regulation

Revision ID: d13de0802292
Revises: e8c7cf61d4c3
Create Date: 2026-06-23 14:10:27.198431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13de0802292'
down_revision: Union[str, Sequence[str], None] = 'e8c7cf61d4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation', sa.Column('rejection_reason', sa.String(length=1000), nullable=True))
    op.add_column('regulation', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation', 'reviewed_at')
    op.drop_column('regulation', 'rejection_reason')
    # ### end Alembic commands ###
