"""Add courses_data to AcademicPlan

Revision ID: ded081a80113
Revises: ccbdbf50f1b2
Create Date: 2026-06-29 01:23:00.403321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded081a80113'
down_revision: Union[str, Sequence[str], None] = 'ccbdbf50f1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_plans', sa.Column('courses_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_plans', 'courses_data')
    # ### end Alembic commands ###
