"""add_student_profile_term_grades_courses_notifications_results

Revision ID: e8c7cf61d4c3
Revises: 3f83bd9ef0c6
Create Date: 2026-06-23 14:04:47.096245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c7cf61d4c3'
down_revision: Union[str, Sequence[str], None] = '3f83bd9ef0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
